config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shortcut/', include('shortcut.urls')),
]

shortcut/urls.py
from django.urls import path

from . import views

app_name = 'shortcut'
urlpatterns = [
    path('', views.WellComeView.as_view(), name='welcome'),
    path('example/', views.ExampleListView.as_view(), name='example_list'),
    path('example/<int:pk>/', views.ExampleDetailView.as_view(), name='example_detail'),
    path('example/create/', views.ExampleCreateView.as_view(), name='example_create'),
    path('example/<int:pk>/update/', views.ExampleUpdateView.as_view(), name='example_update'),
    path('example/<int:pk>/delete/', views.ExampleDeleteView.as_view(), name='example_delete'),
]

shortcut/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(verbose_name='名前', max_length=100)
    description = models.TextField(verbose_name='詳細', blank=True)


class Example(models.Model):
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.CASCADE, blank=True, null=True)
    operation = models.CharField(verbose_name='操作', max_length=100)
    result = models.CharField(verbose_name='结果', max_length=100)
    description = models.TextField(verbose_name='詳細', blank=True)

shortcut/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from shortcut.models import Example


# Create your views here.
class WellComeView(TemplateView):
    template_name = 'shortcut/welcome.html'


class ExampleListView(ListView):
    model = Example
    template_name = 'shortcut/example_list.html'


class ExampleDetailView(DetailView):
    model = Example
    template_name = 'shortcut/example_detail.html'


class ExampleCreateView(CreateView):
    model = Example
    template_name = 'shortcut/example_form.html'
    fields = ['operation', 'result', 'description']
    success_url = '/shortcut/example/'


class ExampleUpdateView(UpdateView):
    model = Example
    template_name = 'shortcut/example_form.html'
    fields = ['operation', 'result', 'description']
    success_url = '/shortcut/example/'


class ExampleDeleteView(DeleteView):
    model = Example
    template_name = 'shortcut/example_confirm_delete.html'
    success_url = '/shortcut/example/'

shortcut/templates/shortcut/example_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <p>{{ object.operation }}</p>
    <p>{{ object.result }}</p>
    <p>{{ object.description|linebreaksbr }}</p>

    <p>削除してもよい？</p>
    <form action="{% url 'shortcut:example_delete' object.pk %}" method="post">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
</div>
</body>
</html>

shortcut/templates/shortcut/example_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <p>{{ object.operation }}</p>
    <p>{{ object.result }}</p>
    <p>{{ object.description|linebreaksbr }}</p>
</div>
<div>
    <a href="{% url 'shortcut:example_update' object.pk %}">編集</a>
    <a href="{% url 'shortcut:example_delete' object.pk %}">削除</a>
    <a href="{% url 'shortcut:example_list' %}">一覧</a>
</div>
</body>
</html>

shortcut/templates/shortcut/example_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <form action="{% url 'shortcut:example_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
</body>
</html>

shortcut/templates/shortcut/example_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for object in object_list %}
    <div>
        <p><a href="{% url 'shortcut:example_detail' object.pk %}">{{ object.id }}</a></p>
        <p>{{ object.operation }}</p>
        <p>{{ object.result }}</p>
    </div>
{% endfor %}
</body>
</html>

shortcut/templates/shortcut/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
ようこそ！我がウェブサイトへ！
</body>
</html>